spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onecake
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


#security

# Enable template caching.
  thymeleaf:
      cache: true
  # Check that the templates location exists.
      check-template-location: true
  # Enable MVC Thymeleaf view resolution.
      enabled: true
  # Template encoding.
      encoding: UTF-8
  # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
      mode: HTML5
  # Prefix that gets prepended to view names when building a URL.
      prefix: classpath:/templates/
  # Suffix that gets appended to view names when building a URL.
      suffix=: .html

