#server:
#  servlet:
#    context-path: /onecake
spring:
  datasource:
          name: onecake
          url: jdbc:mysql://localhost:3306/onecake?useUnicode=true&characterEncoding=UTF8
          username: root
          password: root
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          druid:
              filters: stat
              maxActive: 20
              initialSize: 1
              maxWait: 60000
              minIdle: 1
              timeBetweenEvictionRunsMillis: 60000
              minEvictableIdleTimeMillis: 300000
              validationQuery: select 'x'
              testWhileIdle: true
              testOnBorrow: false
              testOnReturn: false
              poolPreparedStatements: true
              maxOpenPreparedStatements: 20

#security

#thymelea模板配置

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

#Mapper
mapper:
  mappers: com.jesse.onecake.mapper.base.BaseMapper

# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"

#Id Generator
id:
  machine: 3
  type: seconds
  method: 0
  version: 0

# 配置swagger
swagger:
    enabled: true
    base-package: com.jesse.onecake
    title: onecake
    version: 1.0.0.SNAPSHOT
    description:
    contact:
        name:
