spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/onecake
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
  datasource:
          name: onecake
          url: jdbc:mysql://localhost:3306/onecake?useUnicode=true&characterEncoding=UTF8
          username: root
          password: root
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          druid:
              filters: stat
              maxActive: 20
              initialSize: 1
              maxWait: 60000
              minIdle: 1
              timeBetweenEvictionRunsMillis: 60000
              minEvictableIdleTimeMillis: 300000
              validationQuery: select 'x'
              testWhileIdle: true
              testOnBorrow: false
              testOnReturn: false
              poolPreparedStatements: true
              maxOpenPreparedStatements: 20

#security

#Enable template caching.
  thymeleaf:
      cache: true
  # Check that the templates location exists.
      check-template-location: true
  # Enable MVC Thymeleaf view resolution.
      enabled: true
  # Template encoding.
      encoding: UTF-8
  # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
      mode: HTML5
  # Prefix that gets prepended to view names when building a URL.
      prefix: classpath:/templates/
  # Suffix that gets appended to view names when building a URL.
      suffix=: .html

#Mapper
mapper:
  mappers: com.jesse.onecake.mapper.BaseMapper

# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"

#Id Generator
id:
  machine: 3
  type: seconds
  method: 0
  version: 0

# 配置swagger
swagger:
    enabled: true
    base-package: com.jesse.onecake
    title: onecake
    version: 1.0.0.SNAPSHOT
    description:
    contact:
        name: